apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-php-fpm
  namespace: lamp-k8s
  labels:
    app: lamp-php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-php-fpm
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lamp-php-fpm
        tier: backend
    spec:
      containers:
      - image: bitnami/php-fpm:8.0
        name: lamp-php-fpm
        ports:
        - containerPort: 9000
          name: lamp-php-fpm
        volumeMounts:
        - name: lamp-phpcontent
          mountPath: /app/
          readOnly: true
      volumes:
      - name: lamp-phpcontent
        configMap:
          name: php-content

